FROM python:3.6

RUN mkdir /decision_trees
WORKDIR /decision_trees
ADD . /decision_trees//
RUN pip install -r requirements.txt

EXPOSE 5000
CMD ["python", "/decision_trees/main.py"]

ENV PYTHONUNBUFFERED=TRUE
ENV PYTHONDONTWRITEBYTECODE=TRUE
ENV PATH="/opt/program:${PATH}"

# Set up the program in the image
COPY decision_trees /opt/program
WORKDIR /opt/program

